version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer-db-ui
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=chatappdb
      - ADMINER_DEFAULT_DB_USER=postgres
      - ADMINER_DEFAULT_DB_PASS=password
    depends_on:
      - postgres
    networks:
      - app-network

  web_chat_app:
    build: .
    container_name: web_chat_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/chatappdb
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=password
      - VK_APP_ID=${VK_APP_ID}
      - VK_REDIRECT_URL=${VK_REDIRECT_URL}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge