# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

# Database Configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: false

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

vk:
  app:
    id: ${VK_APP_ID}
  redirect:
    url: ${VK_REDIRECT_URL}

# WebSocket Configuration
websocket:
  path: /ws