logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8180

spring:
  application:
    name: chat

# Database Configuration
  datasource:
    url: ${CHAT_APP_DB_URL:jdbc:postgresql://localhost:5432/db}
    username: ${CHAT_APP_DB_USER:postgres}
    password: ${CHAT_APP_DB_PWD:postgres}
    driver-class-name: org.postgresql.Driver

# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

# GraphQL configuration
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  sql:
    init:
      mode: always

# VK OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          vk:
            client-id: ${VK_CLIENT_ID:vk_app_id}
            client-secret: ${VK_CLIENT_SECRET:vk_app_secret}
            client-name: VK
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            pkce-enabled: true
            scope: email
#            redirect-uri: "http://localhost/login/oauth2/code/vk"
            redirect-uri: "https://cs784143.tw1.ru/login/oauth2/code/vk"
        provider:
          vk:
            authorization-uri: https://id.vk.com
            token-uri: https://id.vk.com
            user-info-uri: https://api.vk.com
            user-name-attribute: response.id
            jwk-set-uri: ""